export const CURRENCIES = [
  { code: 'ZAR', symbol: 'R' }, { code: 'USD', symbol: '$' }, { code: 'EUR', symbol: '€' }, { code: 'GBP', symbol: '£' },
  { code: 'AUD', symbol: 'A$' }, { code: 'CAD', symbol: 'C$' }, { code: 'JPY', symbol: '¥' }, { code: 'INR', symbol: '₹' },
  { code: 'BRL', symbol: 'R$' }, { code: 'NGN', symbol: '₦' }, { code: 'KES', symbol: 'KSh' }, { code: 'AED', symbol: 'د.إ' },
  { code: 'CNY', symbol: '¥' }, { code: 'CHF', symbol: 'CHF' }, { code: 'NZD', symbol: 'NZ$' }, { code: 'MXN', symbol: 'MX$' },
  { code: 'SEK', symbol: 'kr' }, { code: 'SGD', symbol: 'S$' },
] as const;
export const STATUSES = { draft: { label: 'Draft', cls: 'badge--draft' }, sent: { label: 'Sent', cls: 'badge--sent' }, accepted: { label: 'Accepted', cls: 'badge--accepted' }, declined: { label: 'Declined', cls: 'badge--declined' }, expired: { label: 'Expired', cls: 'badge--expired' } } as const;
export const UNITS = [
  { value: 'each', label: 'Each' }, { value: 'hour', label: 'Hour' }, { value: 'day', label: 'Day' }, { value: 'sqm', label: 'Per m²' }, { value: 'sqft', label: 'Per ft²' },
  { value: 'kg', label: 'Per kg' }, { value: 'km', label: 'Per km' }, { value: 'unit', label: 'Unit' }, { value: 'lot', label: 'Lot' }, { value: 'month', label: 'Month' },
  { value: 'project', label: 'Project' }, { value: 'session', label: 'Session' }, { value: 'page', label: 'Page' }, { value: 'word', label: 'Word' }, { value: 'metre', label: 'Metre' }, { value: 'litre', label: 'Litre' },
];
export const uid = () => typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);
export function money(a: number, c = 'ZAR') { try { return new Intl.NumberFormat('en', { style: 'currency', currency: c }).format(Number.isFinite(a) ? a : 0); } catch { return `${CURRENCIES.find(x => x.code === c)?.symbol || ''}${(Number.isFinite(a) ? a : 0).toFixed(2)}`; } }
export function fmtDate(iso?: string) { if (!iso) return 'Not set'; const d = new Date(iso); return Number.isNaN(d.valueOf()) ? 'Not set' : d.toLocaleDateString('en', { day: 'numeric', month: 'short', year: 'numeric' }); }
export function minorToMajor(value: number, currency = 'ZAR') {
  return Number(value || 0) / (currency === 'JPY' ? 1 : 100);
}
export function calcTotals(items: any[], tax: number, disc = 0, currency = 'ZAR') { const digits = currency === 'JPY' ? 0 : 2; const factor = 10 ** digits; const round = (v: number) => Math.round((v + Number.EPSILON) * factor) / factor; const line = round(items.reduce((sum, i) => sum + round((Number(i.quantity) || 0) * (Number(i.unitPrice) || 0)), 0)); const discountAmt = round(line * (disc / 100)); const sub = round(line - discountAmt); const taxAmt = round(sub * (tax / 100)); return { line, discountAmt, sub, tax: taxAmt, total: round(sub + taxAmt) }; }
export function newQuote(cur?: string) { return { quoteNumber: '', title: '', clientId: '', clientName: '', clientEmail: '', clientUrl: '', status: 'draft', currency: cur || 'ZAR', taxPercent: 0, discountPercent: 0, validityDays: 30, paymentTermsDays: 30, notes: '', createdAt: new Date().toISOString(), items: [{ id: uid(), description: '', quantity: 1, unitPrice: 0, catalogId: '' }], version: 1 }; }
export function newClient() { return { name: '', company: '', email: '', phone: '', address: '', website: '', notes: '' }; }
export function newProduct() { return { name: '', category: '', description: '', unitPrice: 0, unit: 'each' }; }
export function validateUrl(url?: string) { if (!url || typeof url !== 'string') return ''; const t = url.trim(); if (!t) return ''; try { const u = new URL(t.includes('://') ? t : `https://${t}`); return ['http:', 'https:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } }
export function esc(s: any) { return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
export async function signQuote(quote: any, owner: any) { const payload = JSON.stringify({ id: quote.id, title: quote.title, items: quote.items, total: calcTotals(quote.items, quote.taxPercent, quote.discountPercent, quote.currency).total, created: quote.createdAt, owner: owner.name || 'Business Quotes App', ownerContact: owner.email || '' }); const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(payload)); return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, '0')).join(''); }

export function buildPrintHtml(q: any, biz: any) {
  const cur = q.currency || 'ZAR';
  const { line, discountAmt, sub, tax, total } = calcTotals(q.items ?? [], q.taxPercent ?? 0, q.discountPercent ?? 0, cur);
  const mc = (v: number) => esc(money(v, cur));
  const num = (v: any) => Number.isFinite(Number(v)) ? Number(v) : 0;
  const itemRows = (q.items ?? []).map((i: any) => `<tr><td>${esc(i.description)}</td><td class="qty">${num(i.quantity)}</td><td class="amount">${mc(i.unitPrice)}</td><td class="amount">${mc(num(i.quantity) * num(i.unitPrice))}</td></tr>`).join('');
  const title = q.title || (q.quoteNumber ? `Quote ${q.quoteNumber}` : 'Quote');
  const dueAt = q.dueAt || (q.createdAt ? (() => { const d = new Date(q.createdAt); d.setDate(d.getDate() + Number(q.paymentTermsDays ?? 30)); return d.toISOString(); })() : '');
  const logo = biz.logo ? `<img src="${esc(biz.logo)}" alt="Business logo" class="logo">` : '';
  const contact = [biz.email, biz.phone, biz.address].filter(Boolean).map(esc).join('<br>');
  const csp = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'none'; object-src 'none'; style-src 'unsafe-inline'; img-src data:;">`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">${csp}<meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#1e2430;max-width:820px;margin:0 auto;padding:36px;line-height:1.45}header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;border-bottom:2px solid #1e2430;padding-bottom:20px}.logo{max-width:220px;max-height:72px;object-fit:contain}.muted{color:#6b7280;font-size:13px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:24px 0}.meta strong{display:block;font-size:11px;text-transform:uppercase;color:#6b7280;margin-bottom:3px}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:9px 8px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px}th{font-size:11px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #111827}.qty{text-align:center}.amount{text-align:right;font-variant-numeric:tabular-nums}.totals{width:320px;margin-left:auto}.totals td{border-bottom:0}.grand td{border-top:2px solid #111827;font-size:16px;font-weight:600}.notes{margin-top:28px;border-top:1px solid #e5e7eb;padding-top:16px;white-space:pre-wrap;font-size:12px}@media print{body{padding:18px}a{text-decoration:none;color:inherit}}</style></head><body><header><div>${logo}<h1>${esc(title)}</h1><div class="muted">${q.quoteNumber ? `Document #${esc(q.quoteNumber)}` : ''}</div></div><div class="muted" style="text-align:right">${esc(biz.name || 'Business Quotes')}<br>${contact}</div></header><div class="meta"><div><strong>Client</strong>${esc(q.clientName || 'Not specified')}${q.clientEmail ? `<br><span class="muted">${esc(q.clientEmail)}</span>` : ''}</div><div><strong>Issued</strong>${esc(fmtDate(q.createdAt))}</div><div><strong>Valid until</strong>${esc(fmtDate(q.validUntil))}</div><div><strong>Payment due</strong>${esc(fmtDate(dueAt))}</div></div><table><thead><tr><th>Description</th><th class="qty">Qty</th><th class="amount">Unit price</th><th class="amount">Line total</th></tr></thead><tbody>${itemRows}</tbody></table><table class="totals"><tr><td class="muted">Line total</td><td class="amount">${mc(line)}</td></tr>${q.discountPercent > 0 ? `<tr><td class="muted">Discount (${num(q.discountPercent)}%)</td><td class="amount">-${mc(discountAmt)}</td></tr>` : ''}<tr><td class="muted">Subtotal</td><td class="amount">${mc(sub)}</td></tr><tr><td class="muted">Tax (${num(q.taxPercent)}%)</td><td class="amount">${mc(tax)}</td></tr><tr class="grand"><td>Total due</td><td class="amount">${mc(total)}</td></tr></table>${q.notes ? `<div class="notes"><strong>Notes / terms</strong><br>${esc(q.notes)}</div>` : ''}<div class="muted" style="margin-top:36px;text-align:center">© ${new Date().getFullYear()} ${esc(biz.name || 'Business Quotes')}</div></body></html>`;
}

function csvCell(v: any) { return `"${String(v ?? '').replace(/"/g, '""')}"`; }
export function buildCsv(q: any, biz: any) { const { line, discountAmt, sub, tax, total } = calcTotals(q.items ?? [], q.taxPercent, q.discountPercent, q.currency); const rows: any[] = [['Quote', q.title, 'Number', q.quoteNumber, 'Date', fmtDate(q.createdAt)], ['Client', q.clientName], q.clientEmail ? ['Client email', q.clientEmail] : null, [], ['Description', 'Qty', 'Unit Price', 'Line Total'], ...(q.items ?? []).map((i: any) => [i.description, i.quantity, i.unitPrice, num(i.quantity) * num(i.unitPrice)]), [], ['', '', 'Line Total', line], q.discountPercent > 0 ? ['', '', `Discount (${q.discountPercent}%)`, -discountAmt] : null, ['', '', 'Subtotal', sub], ['', '', `Tax (${q.taxPercent}%)`, tax], ['', '', 'TOTAL', total], [], [`© ${new Date().getFullYear()} ${biz.name || 'Business Quotes'}`]]; return rows.filter(Boolean).map(r => r.map(csvCell).join(',')).join('\n'); }
function num(v: any) { return Number.isFinite(Number(v)) ? Number(v) : 0; }
